#!/usr/bin/env python3
"""OPS-DIRECTIONAL-LABEL-HALT-W1 — per-venue directional-label freshness canary.

The incident this makes impossible-to-miss: 8 venues' `directional_labels`
production silently starved for 16 days (2026-07-04 → 07-21) while every
venue kept EMITTING signals — nothing compared "venues emitting" against
"venues labelling". This canary is the input/output-counter-mismatch form
(skill: silent-producer-halt-via-input-output-counter-mismatch): it fires
ONLY when a venue's signals are ACCRUING (input flowing) and its newest
labeled signal lags beyond the tier SLO (output stuck).

Two-tier SLO (Mr.1 venue policy 2026-07-21, wave spec R4):
  * MAJORS  {BINANCE, BYBIT, OKX, BITGET, HL} — <24h; pages via
    send_telegram.sh AFTER 2 CONSECUTIVE daily breaches (the sustained-drift
    criterion; the wrapper owns severity/cooldown/DRY_RUN/fail-open gates —
    consumers MUST NOT re-implement those).
  * LONG-TAIL (everything else; new venues default here) — <72h; digest
    line only, never pages.

Cron: 41 6 * * * (off-:00; after the nightly labeler budget window ends).
State: /var/lib/algovault-monitoring/label-freshness-state.json
Digest artifact (all venues, every run): /var/lib/algovault-monitoring/label-freshness-digest.txt
Log: /var/log/directional-label-freshness.log (cron appends)

Reads postgres HOST-SIDE via `docker exec <pg-ctr> psql -tA -F'|'` (the
host-bash psql pattern — never `node -e`). Fail-open: any probe/IO error
logs and exits 0 (cron retries tomorrow; the labeler itself is unaffected).

Test seams (hermetic suite: test-directional-label-freshness.py):
  LF_PSQL_CMD    override the psql command (default: docker exec … psql …)
  LF_STATE_FILE  state path        LF_DIGEST_FILE digest path
  LF_WRAPPER     send_telegram.sh path
  LF_NOW_EPOCH   freeze "now"      --force-stale VENUE  synthetic breach
                                   (pair with ALGOVAULT_TG_TEST_INERT=1 — runbook §6)

SEC-13: the sanctioned smoke used to REQUIRE DRY_RUN_TG=1, which is NOT inert —
send_telegram.sh writes the 24h cooldown marker on that path ("marker written for
cooldown smokes"). So a smoke BURNED the real cooldown: for the next 24h a genuine
MAJOR-venue label-production halt — the exact 16-day silent starvation this canary
exists to catch — was SUPPRESSED_COOLDOWN and never reached Telegram. And a second
smoke false-greened, being cooldown-suppressed rather than healthy.
ALGOVAULT_TG_TEST_INERT=1 exits BEFORE the cooldown gate and writes no marker.
Keep DRY_RUN_TG only for a test whose assertion IS the cooldown (clear the marker first).

Thresholds carry `defensive-reductions-to-revisit.md` rows.
TODO: revisit by 2026-08-04 — tier SLOs vs 30d of observed lag telemetry.
"""
from __future__ import annotations

import json
import os
import shlex
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import detector_envelope as de  # noqa: E402  (host-local sibling; see the inventory row)
import labeler_truncation_attribution as lta  # noqa: E402  (host-local sibling; see the inventory row)

def load_tiers(path: str | None = None):
    """OPS-LABEL-FRESHNESS-W1 R2 — single-derivation with the labeler. Read the emitted SoT
    mirror (venue-slo-tiers.json, byte-locked to src/lib/venue-slo-tiers.ts by the vitest
    suite + regenerated by scripts/emit-venue-slo-tiers.mjs). The scheduler and this monitor
    MUST agree on who is a major or they optimise/measure different objectives (the H1 bug).
    Fail-SAFE to embedded defaults so a missing/corrupt mirror never blinds the canary; the
    tier-mirror drift check catches a stale host sync separately."""
    path = path or os.environ.get("LF_TIERS_FILE", str(Path(__file__).parent / "venue-slo-tiers.json"))
    try:
        d = json.loads(Path(path).read_text())
        majors = set(d["majors"])
        maj, lt, spec = int(d["major_slo_hours"]), int(d["longtail_slo_hours"]), str(d["barrier_spec"])
        if majors and maj > 0 and lt > 0 and spec:
            return majors, maj, lt, spec
    except Exception as exc:  # fail-safe to defaults; never crash the canary on a mirror hiccup
        print(f"[label-freshness] TIERS_FALLBACK {path}: {exc}", file=sys.stderr)
    return {"BINANCE", "BYBIT", "OKX", "BITGET", "HL"}, 24, 72, "tau1.0-floor0.30-v1"


MAJORS, MAJOR_SLO_H, LONGTAIL_SLO_H, BARRIER_SPEC = load_tiers()


# ── OPS-BDIR-V3-PANEL-READINESS-W1 CH2 — the FULL-eligible panel and the COVERAGE arm ─────────────
#
# The ONE page-worthy venue set for coverage and capacity (architect ruling Q-F, 2026-09-26): the
# venues the B-DIR v3 FULL test can still admit. Read from the SAME tier mirror as the majors
# (`full_panel_venues`, emitted from src/lib/venue-slo-tiers.ts), fail-SAFE to the ruled set, so the
# labeler's venue order and this canary's paging set can never disagree.
FULL_PANEL_DEFAULT = frozenset({"KUCOIN", "BITGET", "OKX", "BINANCE", "BYBIT"})


def load_full_panel(path: str | None = None) -> frozenset[str]:
    path = path or os.environ.get("LF_TIERS_FILE", str(Path(__file__).parent / "venue-slo-tiers.json"))
    try:
        venues = json.loads(Path(path).read_text())["full_panel_venues"]
        if isinstance(venues, list) and venues and all(isinstance(v, str) and v for v in venues):
            return frozenset(venues)
    except Exception as exc:  # fail-safe: never blind the canary on a mirror hiccup
        print(f"[label-freshness] FULL_PANEL_FALLBACK {path}: {exc}", file=sys.stderr)
    return FULL_PANEL_DEFAULT


FULL_PANEL = load_full_panel()

# The coverage arm: labelled / emitted on the PRIMARY spec — the FULL test's panel rule (c) with its
# own denominator (emitted BUY/SELL) — over the trailing 7 days, on rows whose label window CLOSED at
# least a day ago, so the nightly had its chance. FAIL below 90 % pages for a FULL-eligible venue;
# every other venue REPORTS with its declared reason. Before this arm the canary measured only the
# FRONTIER (the newest labelled row), which an alphabetical prefix keeps fresh at 40 % coverage.
COVERAGE_WINDOW_D = 7
COVERAGE_GRACE_S = 86_400
COVERAGE_FLOOR = 0.90
COVERAGE_ALERT_ID = "DIRECTIONAL_LABEL_COVERAGE_SHORTFALL"
# A FULL venue below the floor that gained at least this much since the previous run is RECOVERING
# (the nightly is closing the gap) and is held, not paged — see coverage_page_decision(). Below
# 2 pp/night the gap is not closing on any useful horizon, so it counts as a stall and pages; and a
# hold never outlives COVERAGE_WINDOW_D consecutive FAIL runs, whatever the gain.
COVERAGE_RECOVERING_MIN_GAIN = 0.02
# Evaluation windows in candles — MUST equal src/scripts/directional-labeler.ts EVAL_CANDLES
# (pinned by tests/unit/directional-label-coverage-arm.test.ts). +2 is the labeler's fetch buffer.
EVAL_W = {"3m": 12, "5m": 12, "15m": 12, "30m": 8, "1h": 8, "2h": 6, "4h": 6, "8h": 4, "12h": 4, "1d": 3}
TF_S = {"3m": 180, "5m": 300, "15m": 900, "30m": 1800, "1h": 3600, "2h": 7200, "4h": 14400,
        "8h": 28800, "12h": 43200, "1d": 86400}
# Declared reasons a non-FULL venue REPORTS instead of paging. Data, not prose: an exemption that
# lives only in a comment gets "fixed" by the next wave enforcing the contract.
REPORT_REASONS = {
    "HL": ("not FULL-eligible: rule (d) fails by candle horizon (76.5% of HL rows are sub-1h; 5m depth "
           "17.48 d); also lane-bound (~1 HL request/min in its slot)"),
}
REPORT_REASON_DEFAULT = ("not FULL-eligible: served after the FULL panel inside the 210-min nightly "
                         "budget (capacity by declaration, ruling Q-F)")


def coverage_sql(now: int) -> str:
    """PURE — returned as a string so the hermetic suite asserts its SHAPE."""
    windows = ", ".join(f"('{tf}', {(w + 2) * TF_S[tf]})" for tf, w in EVAL_W.items())
    return (
        "SET default_transaction_read_only=on; "
        f"WITH w(timeframe, window_s) AS (VALUES {windows}) "
        "SELECT s.exchange, COUNT(*) AS emitted, COUNT(d.signal_id) AS labelled "
        "FROM signals s JOIN w ON w.timeframe = s.timeframe "
        "LEFT JOIN directional_labels d ON d.signal_id = s.id "
        f"AND d.barrier_spec = '{BARRIER_SPEC}' "
        "WHERE s.signal IN ('BUY','SELL') "
        f"AND s.created_at >= {now - COVERAGE_WINDOW_D * 86400} "
        f"AND s.created_at + w.window_s + {COVERAGE_GRACE_S} <= {now} "
        "AND s.exchange NOT IN (SELECT exchange_id FROM venues WHERE status = 'retired') "
        "GROUP BY 1 ORDER BY 1;"
    )


def coverage_census(now: int) -> list[tuple[str, int, int]]:
    cmd = os.environ.get("LF_COVERAGE_CMD", PSQL_DEFAULT)
    out = subprocess.run(cmd.split() + ["-c", coverage_sql(now)], capture_output=True, text=True, timeout=180)
    if out.returncode != 0:
        raise RuntimeError(f"coverage psql rc={out.returncode}: {out.stderr.strip()[:160]}")
    rows: list[tuple[str, int, int]] = []
    for line in out.stdout.strip().splitlines():
        if "|" not in line:
            continue  # SET tag / noise
        parts = line.split("|")
        if len(parts) != 3 or not parts[1].strip().isdigit() or not parts[2].strip().isdigit():
            raise ValueError(f"unparseable coverage row {line[:80]!r}")
        rows.append((parts[0].strip(), int(parts[1]), int(parts[2])))
    return rows


def evaluate_coverage(rows: list[tuple[str, int, int]], full: frozenset[str]):
    """PURE. Returns (verdict, lines, failing) — verdict over the FULL venues only.
    A FULL venue with no measured rows is INDETERMINATE (we cannot vouch for it); a check that could
    not run never reads as PASS. Non-FULL venues are reported, never counted into the verdict."""
    by = {v: (e, lab) for v, e, lab in rows}
    lines, verdicts, failing = [], [], []
    for venue in sorted(set(by) | set(full)):
        emitted, labelled = by.get(venue, (0, 0))
        ratio = labelled / emitted if emitted else None
        arm = "PAGE" if venue in full else "REPORT"
        if ratio is None:
            v = "INDETERMINATE"
        else:
            v = "PASS" if ratio >= COVERAGE_FLOOR else "FAIL"
        ratio_s = "n/a" if ratio is None else f"{ratio * 100:.1f}%"
        line = f"COVERAGE {venue} emitted={emitted} labelled={labelled} ratio={ratio_s} arm={arm} verdict={v}"
        if arm == "REPORT" and v != "PASS":
            line += f" reason={REPORT_REASONS.get(venue, REPORT_REASON_DEFAULT)}"
        lines.append(line)
        if arm == "PAGE":
            verdicts.append(v)
            if v == "FAIL":
                failing.append((venue, emitted, labelled, ratio_s))
    if "FAIL" in verdicts:
        verdict = "FAIL"
    elif "INDETERMINATE" in verdicts or not verdicts:
        verdict = "INDETERMINATE"
    else:
        verdict = "PASS"
    return verdict, lines, failing


def coverage_page_decision(failing, prior: dict, full: frozenset[str], measured: set[str]):
    """PURE. Which FAIL venues page NOW, which are held and why, and the coverage state to persist.

    The verdict (token) is not decided here — a venue below 90% is FAIL whatever this returns. Only
    the PAGE is gated, with this canary's own sustained-drift idiom: the nightly labeler IS the
    recovery for a coverage gap, so paging before it had a night to act is recovery chatter.
      * day 1 (first consecutive FAIL run)                              → hold
      * later, and gained >= COVERAGE_RECOVERING_MIN_GAIN since the last run → hold (recovering)
      * later, and not gaining                                          → PAGE (the recovery stalled)
      * past COVERAGE_WINDOW_D consecutive FAIL runs                    → PAGE whatever the gain (the
        7-day window has fully turned over, so "still catching up" no longer explains it)
    State keeps FULL venues currently in FAIL only; a PASS forgets the streak. A FULL venue this run
    could not measure keeps its prior entry untouched — no reset, no advance."""
    to_page, held, state = [], [], {}
    for v in full:
        if v not in measured and v in prior:
            state[v] = prior[v]
    for venue, emitted, labelled, ratio_s in failing:
        ratio = labelled / emitted
        p = prior.get(venue) if isinstance(prior.get(venue), dict) else {}
        fails = int(p.get("fails", 0)) + 1
        prev = p.get("ratio")
        gain = None if prev is None else ratio - float(prev)
        state[venue] = {"ratio": round(ratio, 4), "fails": fails}
        prev_s = "n/a" if prev is None else f"{float(prev) * 100:.1f}%"
        entry = (venue, emitted, labelled, ratio_s, fails, prev_s)
        if fails > COVERAGE_WINDOW_D:
            to_page.append(entry)
        elif fails < CONSECUTIVE_TO_PAGE:
            held.append((venue, fails, f"day {fails} — the sustained-drift gate holds the page until day "
                                       f"{CONSECUTIVE_TO_PAGE}"))
        elif gain is not None and gain >= COVERAGE_RECOVERING_MIN_GAIN - 1e-9:
            held.append((venue, fails, f"recovering {gain * 100:+.1f} pp since the previous run ({prev_s} → {ratio_s})"))
        else:
            to_page.append(entry)
    return to_page, held, state


def coverage_arm(wrapper: str, now: int, prior: dict | None = None) -> tuple[str, dict]:
    """Run the arm: positive per-venue lines, ONE token, page on a SUSTAINED FAIL that is not
    recovering, clear on PASS, silent on INDETERMINATE. Fail-open like the rest of this canary: a
    read failure is INDETERMINATE and leaves the coverage state exactly as it was. Returns
    (verdict, coverage state to persist)."""
    prior = prior if isinstance(prior, dict) else {}
    try:
        rows = coverage_census(now)
        verdict, lines, failing = evaluate_coverage(rows, FULL_PANEL)
    except Exception as exc:
        log(f"COVERAGE INDETERMINATE — could not read the coverage census: {str(exc)[:160]}")
        print("DIRECTIONAL_LABEL_COVERAGE_VERDICT=INDETERMINATE")
        return "INDETERMINATE", prior
    for line in lines:
        log(line)
    measured = {v for v, e, _ in rows if e}
    to_page, held, state = coverage_page_decision(failing, prior, FULL_PANEL, measured)
    for venue, fails, why in held:
        log(f"COVERAGE_HOLD {venue} fails={fails} — {why}")
    if to_page:
        body = "\n".join([
            f"🛑 {COVERAGE_ALERT_ID}",
            "Directional-label COVERAGE below 90% on a venue the B-DIR v3 FULL test can still admit "
            "(panel rule (c)), and the nightly is not closing the gap:",
            *[f"venue {v}: {lab} of {e} emitted rows labelled = {r} over the trailing "
              f"{COVERAGE_WINDOW_D} d (rows whose label window closed >= 1 d ago); {n} consecutive "
              f"FAIL runs, previous run {p}" for v, e, lab, r, n, p in to_page],
            "Action: dispatch OPS-LABEL-COVERAGE-W{NEXT} via Cowork → Claude Code",
            "Source log: /var/log/directional-label-freshness.log",
        ])
        try:
            subprocess.run([wrapper, COVERAGE_ALERT_ID, SEVERITY, "-"], input=body, text=True, timeout=60)
            log(f"COVERAGE_PAGE_SENT venues={[v for v, *_ in to_page]}")
        except Exception as exc:
            log(f"COVERAGE FAIL_OPEN wrapper error: {exc}")
    elif verdict == "PASS":
        try:
            # stdin closed: a clear carries no body, and must never block on an inherited open stdin
            subprocess.run([wrapper, "--clear", COVERAGE_ALERT_ID, "every FULL-eligible venue >= 90% coverage"],
                           stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=60)
        except Exception as exc:
            log(f"COVERAGE clear FAIL_OPEN: {exc}")
    print(f"DIRECTIONAL_LABEL_COVERAGE_VERDICT={verdict}")
    return verdict, state
INPUT_FLOWING_H = 48          # venue must have >=1 eligible signal this recent
CONSECUTIVE_TO_PAGE = 2       # sustained-drift criterion (majors only)

# OPS-LABEL-FRESHNESS-W1 R3 — auto-recovery (Detect→Recover→Verify→Alert): a bounded, flock'd,
# paced targeted re-label of a lagging major BEFORE the page. A major that heals is SILENT
# (recovery alerts are noise, CLAUDE.md); only a major that fails recovery reaches the page.
RECOVERY_ENABLED = os.environ.get("LF_RECOVERY_ENABLED", "1") == "1"
RECOVERY_DRY_RUN = os.environ.get("LF_RECOVERY_DRY_RUN") == "1"       # autopilot first-fire gate
RECOVERY_CAP_MIN = int(os.environ.get("LF_RECOVERY_CAP_MIN", "20"))   # TODO: revisit by 2026-08-07
RECOVERY_LOCK = os.environ.get("LF_RECOVERY_LOCK", "/var/lock/algovault-label-backfill.lock")
LABELER_CTR = os.environ.get("LF_LABELER_CTR", "crypto-quant-signal-mcp-mcp-server-1")

ALERT_ID = "DIRECTIONAL_LABEL_FRESHNESS_BREACH"
SEVERITY = "CRITICAL_PERSISTENT"  # design-time classification: sustained
# data-pipeline death needing an operator dispatch (runbook contract #4).

# NOTE: no -F flag — psql's unaligned default separator already IS `|`, and this
# command is split() for subprocess (NO shell), so a quoted -F'|' would reach
# psql with LITERAL quotes and silently break every row (caught by live smoke).
# OPS-SEC-DB-LEAST-PRIV-W2: reads as `aoe_readonly`, not the bootstrap superuser.
# This connects over the postgres container's `local ... trust` line, so the role is
# chosen purely by -U and needs no credential — which is exactly why a DSN rotation can
# never re-point it, and why it had to be changed here by hand. `aoe_readonly` holds
# SELECT on `signals` + `directional_labels` (live-verified), which is all this census
# reads; it cannot write, so the read-only intent is now enforced by the role rather
# than only by `SET default_transaction_read_only=on` below.
PSQL_DEFAULT = (
    "docker exec crypto-quant-signal-mcp-postgres-1 "
    "psql -U aoe_readonly -d signal_performance -tA"
)

CENSUS_SQL = (
    "SET default_transaction_read_only=on; "
    "SELECT s.exchange, MAX(s.created_at) AS newest_signal, "
    "MAX(s.created_at) FILTER (WHERE d.signal_id IS NOT NULL) AS newest_labeled "
    "FROM signals s LEFT JOIN directional_labels d "
    f"ON d.signal_id = s.id AND d.barrier_spec = '{BARRIER_SPEC}' "
    "WHERE s.signal IN ('BUY','SELL') AND s.pfe_return_pct IS NOT NULL "
    "AND s.timeframe <> '1m' GROUP BY 1 ORDER BY 1;"
)

# OPS-VENUE-STATUS-DERIVED-REGISTRIES-W1 (Q3): a venue RETIRED in the `venues` table is not a
# monitored producer — the seed loop stopped emitting its signals and the labeler stopped labelling
# them (both status-derived). Its stranded pre-retirement signals would otherwise read as "recent
# input, lagging labels" and show a cosmetic BREACH for up to INPUT_FLOWING_H hours. We render it
# `retired` instead, never BREACH. `aoe_readonly` holds SELECT on `venues` (probed 2026-08-27). A
# SEPARATE LF_RETIRED_CMD seam (defaults to the same psql) lets the test inject it independently.
RETIRED_SQL = (
    "SET default_transaction_read_only=on; "
    "SELECT exchange_id FROM venues WHERE status = 'retired';"
)


def now_epoch() -> int:
    return int(os.environ.get("LF_NOW_EPOCH") or time.time())


def log(msg: str) -> None:
    print(f"{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())} [label-freshness] {msg}")


def census() -> list[tuple[str, int, int | None]]:
    cmd = os.environ.get("LF_PSQL_CMD", PSQL_DEFAULT)
    out = subprocess.run(
        cmd.split() + ["-c", CENSUS_SQL], capture_output=True, text=True, timeout=120
    )
    if out.returncode != 0:
        raise RuntimeError(f"psql failed rc={out.returncode}: {out.stderr.strip()[:200]}")
    rows: list[tuple[str, int, int | None]] = []
    for line in out.stdout.strip().splitlines():
        if "|" not in line:
            continue  # SET tag / noise
        venue, newest_sig, newest_lab = (line.split("|") + [""])[:3]
        if not venue or not newest_sig.strip().isdigit():
            continue
        rows.append((venue.strip(), int(newest_sig), int(newest_lab) if newest_lab.strip().isdigit() else None))
    return rows


def retired_set() -> frozenset[str]:
    """Retired venue ids, to suppress a cosmetic BREACH on a deliberately-retired venue.
    FAIL-SAFE: any error yields an EMPTY set — a retired venue then merely keeps its old (long-tail,
    never-paging) digest line; we never SUPPRESS a real major breach, because a major is never retired."""
    cmd = os.environ.get("LF_RETIRED_CMD", PSQL_DEFAULT)
    try:
        out = subprocess.run(cmd.split() + ["-c", RETIRED_SQL], capture_output=True, text=True, timeout=60)
        if out.returncode != 0:
            log(f"retired_set psql rc={out.returncode}: {out.stderr.strip()[:120]} — treating as none")
            return frozenset()
        return frozenset(s for line in out.stdout.strip().splitlines() if (s := line.strip()) and s != "SET")
    except Exception as exc:
        log(f"retired_set error: {exc} — treating as none")
        return frozenset()


def evaluate(rows, force_stale: str | None, now: int, retired: frozenset[str] = frozenset()):
    """Pure classification: returns (digest_lines, major_breaches, longtail_breaches)."""
    digest, majors_bad, tail_bad = [], [], []
    for venue, newest_sig, newest_lab in sorted(rows):
        if venue in retired:
            # OPS-VENUE-STATUS-DERIVED-REGISTRIES-W1 (Q3): a retired venue is not a monitored producer.
            # Render `retired`, never BREACH, never a page — its stranded pre-retirement signals would
            # otherwise read as recent-input / lagging-labels for up to INPUT_FLOWING_H hours.
            digest.append(f"{venue:9s} {'retired':9s} lag={'n/a':>8s} slo=-   retired")
            continue
        tier = "major" if venue in MAJORS else "long-tail"
        slo_h = MAJOR_SLO_H if venue in MAJORS else LONGTAIL_SLO_H
        input_flowing = (now - newest_sig) <= INPUT_FLOWING_H * 3600
        lag_h = (now - newest_lab) / 3600 if newest_lab else float("inf")
        if force_stale and venue == force_stale:
            lag_h, input_flowing = 999.0, True  # synthetic breach (ALGOVAULT_TG_TEST_INERT smoke)
        breach = input_flowing and lag_h > slo_h
        mark = "BREACH" if breach else ("idle" if not input_flowing else "ok")
        lag_s = "never" if lag_h == float("inf") else f"{lag_h:.1f}h"
        digest.append(f"{venue:9s} {tier:9s} lag={lag_s:>8s} slo={slo_h}h {mark}")
        if breach:
            (majors_bad if venue in MAJORS else tail_bad).append((venue, lag_s))
    return digest, majors_bad, tail_bad


def build_alert_body(majors_bad, consecutive: dict[str, int]) -> str:
    lines = [f"🛑 {ALERT_ID}",
             f"Directional-label freshness SLO breach on MAJOR venue(s): "
             + ", ".join(f"{v} lag={s} (>{MAJOR_SLO_H}h)" for v, s in majors_bad),
             "Context: signals ARE accruing on these venues while labels lag — the "
             "silent-producer-halt class; consecutive daily fails: "
             + ", ".join(f"{v}={consecutive.get(v, 0)}" for v, _ in majors_bad)
             + f" (pages at {CONSECUTIVE_TO_PAGE}).",
             "Action: dispatch OPS-LABEL-FRESHNESS-W{NEXT} via Cowork → Claude Code",
             "Audit shape: audits/OPS-DIRECTIONAL-LABEL-HALT-W1-endpoint-truth.md",
             "Source log: /var/log/directional-label-freshness.log"]
    return "\n".join(lines)


def attempt_recovery(venue: str) -> bool:
    """R3 RECOVER: a bounded, flock'd, paced targeted re-label of ONE lagging major. Idempotent
    (ON CONFLICT) + fail-open. `flock -n` so it never collides with the 02:23 nightly or the
    triage backfill (same lock). Returns True iff a real (non-dry-run) backfill ran to exit 0."""
    override = os.environ.get("LF_RECOVERY_CMD")  # test seam (parallels LF_PSQL_CMD)
    cmd = (shlex.split(override) + [venue]) if override else [
        "flock", "-n", RECOVERY_LOCK,
        "docker", "exec", LABELER_CTR, "node", "dist/scripts/backfill-directional-labels.js",
        "--venue", venue, "--lookback-days", "21",
        "--time-budget-min", str(RECOVERY_CAP_MIN), "--venue-budget-min", str(RECOVERY_CAP_MIN),
    ]
    if RECOVERY_DRY_RUN:
        log(f"RECOVERY_DRY_RUN would run: {' '.join(cmd)}")
        return False
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=(RECOVERY_CAP_MIN + 5) * 60)
    except Exception as exc:  # timeout / spawn error — fail-open; the page path still runs
        log(f"RECOVERY venue={venue} FAIL_OPEN: {exc}")
        return False
    if r.returncode == 0:
        log(f"RECOVERY ran targeted re-label venue={venue} cap={RECOVERY_CAP_MIN}m")
        return True
    # D4 — 137 is 128+9, SIGKILL. Folding it into "flock busy or backfill error" destroys the
    # diagnosis at the point of capture: on 2026-08-22 the BYBIT recovery died 137 because a
    # deploy recreated the container mid-flight, and the log said only that it "did not run".
    cause = _classify_recovery_exit(r.returncode)
    log(f"RECOVERY venue={venue} did-not-run exit={r.returncode} ({cause}) — fail-open: {r.stderr.strip()[:160]}")
    return False


def _classify_recovery_exit(code: int) -> str:
    """Name the cause instead of a catch-all. A diagnosable cause folded into a bucket is
    evidence destroyed at the point of capture."""
    if code == 137:
        return "SIGKILL (128+9) — the container was stopped mid-run, typically a deploy recreate"
    if code == 143:
        return "SIGTERM (128+15) — the process was asked to stop mid-run"
    if code == 1:
        return "flock busy or backfill error"
    return "unclassified non-zero exit"


def forward_capacity_signal(wrapper: str, log_path: str | None = None, still_breaching=None, attempted=None) -> bool:
    """Forward the labeler's DETECTOR_ENVELOPE (Objective #2) from the LAST nightly run.

    OPS-MONITORING-SIGNAL-CONTRACT-W1 CH3 — D2 + D3.

    D2. The body is rendered ENTIRELY from `evidence`. The previous body asserted "SLO-ordered,
    so majors were served first; the shortfall is the long-tail overflow" — both halves false,
    and structurally inverted, because majors carry a 24h SLO against long-tail 72h and are
    therefore the venues the selector is MOST likely to name. Prose in an alert body is a claim
    nobody re-checks when the code beneath it changes.

    D3. Two refusals, and they are different refusals:
      * an envelope whose `run_id` is not the CURRENT run is refused by `decide()`;
      * a venue that this script's own recovery step has already REPAIRED is dropped here, and
        if nothing is left in danger, nothing is forwarded. On 2026-08-22 the page named BINANCE
        and BITGET at 06:53:19Z — 8m39s and 49s after this very script repaired them.

    Fail-open; returns True iff a page was forwarded.
    """
    log_path = log_path or os.environ.get("LF_LABELER_LOG", "/var/log/carry-labeler.log")
    try:
        lines = Path(log_path).read_text(errors="replace").splitlines()[-6000:]
    except Exception as exc:
        log(f"CAPACITY_SIGNAL FAIL_OPEN: cannot read {log_path}: {exc}")
        return False

    # The CURRENT run id, as the PRODUCER printed it — never re-derived from a log timestamp.
    run_ids = [l.split("run_id=", 1)[1].strip() for l in lines if "[detector-run] run_id=" in l]
    current = run_ids[-1] if run_ids else None

    starts = [i for i, l in enumerate(lines) if "DWR backfill start" in l]
    scope = lines[starts[-1]:] if starts else lines
    raw = next((l for l in reversed(scope) if "[detector-envelope]" in l), None)
    if raw:
        try:
            env = json.loads(raw.split("[detector-envelope]", 1)[1].strip())
        except Exception as exc:
            log(f"CAPACITY_SIGNAL INDETERMINATE: envelope is not parseable JSON: {exc}")
            return False
    else:
        # TRANSITIONAL — the legacy `[capacity-shortfall]` marker.
        #
        # This consumer is installed by reviewed SSH; the PRODUCER ships in the container image
        # and lands on its own deploy cadence. Between the two, the host runs the new consumer
        # against a producer that still emits the old marker.
        #
        # WHAT THIS BRANCH ACTUALLY BUYS, stated precisely because the first version of this
        # comment overclaimed it. It does NOT deliver a page during that window: a log written
        # by the old producer carries no `[detector-run] run_id=` line either, so `current` is
        # None and `decide()` refuses on IDENTITY before the verdict is ever consulted —
        # MEASURED on the live host against the real 2026-08-22 log, which refused with
        # "consumer could not determine the current run id". What it buys is that the refusal is
        # REASONED and LOGGED rather than the consumer falling out at "no envelope found", and
        # that the moment a run id IS present the marker is adapted rather than dropped. The
        # window is therefore a VISIBLE INDETERMINATE, not a delivered page and not silence —
        # which is the contract, not a workaround for it.
        #
        # A legacy marker carries NO run outcome, so we genuinely cannot tell whether the run
        # that wrote it finished. `run_outcome: unknown` is not conclusive, so the contract
        # forces INDETERMINATE — the honest answer, and the same one the incident deserved.
        legacy = next((l for l in reversed(scope) if "[capacity-shortfall]" in l), None)
        if not legacy:
            log("CAPACITY_SIGNAL INDETERMINATE: the last run emitted no [detector-envelope] "
                "and no legacy [capacity-shortfall] line")
            return False
        detail = legacy.split("[capacity-shortfall]", 1)[1].strip()
        ev = {}
        for tok in detail.split():
            if "=" in tok:
                k, v = tok.split("=", 1)
                ev[k] = v
        ev.pop("recommended_wave", None)   # a remedy is not a measurement
        now_iso = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        env = {
            "schema_version": 1, "detector": "directional-label-capacity",
            "verdict": "INDETERMINATE", "run_id": current or "legacy-marker",
            "run_started_at": now_iso, "run_outcome": "unknown",
            "produced_at": now_iso,
            "observation_window": {"from": now_iso, "to": now_iso},
            "evidence": ev or {"legacy_marker": "present"},
        }
        log("CAPACITY_SIGNAL legacy [capacity-shortfall] marker adapted — run_outcome=unknown, "
            "so no capacity conclusion is possible from it")

    try:
        schema = de.load_schema()
    except Exception as exc:
        # An unreadable contract is INDETERMINATE, never a permissive default.
        log(f"CAPACITY_SIGNAL INDETERMINATE: cannot read the envelope schema: {exc}")
        return False

    decision = de.decide(env, current, schema=schema)
    if decision.action == de.REFUSE:
        log(f"CAPACITY_SIGNAL REFUSED ({decision.verdict}): {decision.reason}")
        return False

    # D3 — drop venues this run's recovery already repaired. `still_breaching is None` means the
    # caller could not determine the post-recovery set, which is NOT the same as "none healed":
    # in that case nothing is dropped and the envelope is forwarded as measured.
    #
    # CORRECTED (OPS-BDIR-V3-PANEL-READINESS-W1 CH2, R0.4 "never fired → fix its predicate"): a venue
    # counts as REPAIRED only if this run's recovery step actually ATTEMPTED it and it no longer
    # breaches. The rule was `named − still_breaching`, but `still_breaching` holds only the
    # frontier-breaching MAJORS — so every long-tail venue, and every major not yet past its frontier
    # SLO, was dropped as "repaired" with no recovery having run for it. That is why this page never
    # fired after 2026-08-27 (measured: 09-26 "dropped ['BYBIT', 'OKX', 'KUCOIN', 'PHEMEX']", none of
    # them attempted). `attempted is None` (unknown) drops nothing, exactly like `still_breaching`.
    named = [v for v in str(env["evidence"].get("unreached_in_danger", "")).split(",") if v and v != "none"]
    if still_breaching is not None and attempted is not None and named:
        healed = [v for v in named if v in attempted and v not in still_breaching]
    else:
        healed = []
    remaining = [v for v in named if v not in healed]
    if healed:
        log(f"CAPACITY_SIGNAL dropped {healed} — repaired by this run's recovery step")
    if named and not remaining:
        log("CAPACITY_SIGNAL REFUSED (PASS): every named venue was repaired before this page")
        return False
    # Ruling Q-F: a capacity CONCLUSION (verdict FAIL) pages only for FULL-eligible venues; a non-FULL
    # venue short of capacity is the declared trade-off and is REPORTED with its reason. A run that
    # could not measure (INDETERMINATE) is still forwarded as-is — that is about the run, not a venue.
    reported: list[str] = []
    if decision.verdict == "FAIL":
        reported = [v for v in remaining if v not in FULL_PANEL]
        remaining = [v for v in remaining if v in FULL_PANEL]
        for v in reported:
            log(f"CAPACITY_SIGNAL REPORTED {v} (not paged) — {REPORT_REASONS.get(v, REPORT_REASON_DEFAULT)}")
        if named and not remaining:
            log("CAPACITY_SIGNAL REFUSED (PASS for the FULL panel): no FULL-eligible venue is in danger")
            return False
    if named:
        env = dict(env)
        env["evidence"] = dict(env["evidence"])
        env["evidence"]["unreached_in_danger"] = ",".join(remaining) or "none"
        env["evidence"]["unreached_count"] = len(remaining)
        env["evidence"]["dropped_after_recovery"] = ",".join(healed) or "none"
        if reported:
            env["evidence"]["reported_not_paged"] = ",".join(reported)

    body = "\n".join([
        f"{'🛑' if decision.verdict == 'FAIL' else '❓'} DIRECTIONAL_LABEL_CAPACITY_SHORTFALL",
        de.render_body(env, schema),
        f"Action: dispatch OPS-LABEL-CAPACITY-W{{NEXT}} via Cowork → Claude Code"
        if decision.verdict == "FAIL" else
        "Action: none — the labeler could not complete its measurement; no capacity claim is made",
        f"Source log: {log_path}",
    ])
    try:
        subprocess.run([wrapper, "DIRECTIONAL_LABEL_CAPACITY_SHORTFALL", "CRITICAL_PERSISTENT", "-"],
                       input=body, text=True, timeout=60)
        log(f"CAPACITY_SIGNAL_FORWARDED verdict={decision.verdict} run={env['run_id']} outcome={env['run_outcome']}")
        return True
    except Exception as exc:
        log(f"CAPACITY_SIGNAL FAIL_OPEN: {exc}")
        return False


def main(argv: list[str]) -> int:
    force_stale = None
    if "--force-stale" in argv:
        i = argv.index("--force-stale")
        force_stale = argv[i + 1] if i + 1 < len(argv) else None
        # SEC-13: accept the INERT lever (preferred — no cooldown marker) or the legacy
        # DRY_RUN_TG (which DOES write the marker and therefore burns the real cooldown).
        inert = os.environ.get("ALGOVAULT_TG_TEST_INERT") == "1"
        dry = os.environ.get("DRY_RUN_TG") == "1"
        if not inert and not dry:
            log("REFUSING --force-stale without ALGOVAULT_TG_TEST_INERT=1 (runbook §6: synthetic fires are silent)")
            return 0
        if dry and not inert:
            log("WARNING --force-stale under DRY_RUN_TG=1 WRITES the 24h cooldown marker and will "
                "suppress the next genuine alert; prefer ALGOVAULT_TG_TEST_INERT=1")
    state_file = Path(os.environ.get("LF_STATE_FILE", "/var/lib/algovault-monitoring/label-freshness-state.json"))
    digest_file = Path(os.environ.get("LF_DIGEST_FILE", "/var/lib/algovault-monitoring/label-freshness-digest.txt"))
    wrapper = os.environ.get("LF_WRAPPER", "/opt/algovault-monitoring/send_telegram.sh")

    # SEC-30 (OPS-AUDIT-REMEDIATION-LOW-W1): a SYNTHETIC breach must never be written into
    # production state. --force-stale marks a venue bad inside evaluate(), that venue lands in
    # majors_bad, majors_bad builds `consecutive`, and `consecutive` is persisted below — so a
    # single smoke run incremented the REAL sustained-drift counter for a healthy venue. The
    # next genuine run then reads an inflated prior and can page a day early, which defeats the
    # entire point of the sustained-drift gate the smoke was exercising.
    #
    # Redirecting the artifacts (rather than filtering the forced venue out of `consecutive`)
    # is deliberate: the smoke still exercises the real read/evaluate/page path end to end, but
    # NOTHING it computes can reach the durable files. A filter would leave the digest write and
    # the `updated` stamp still landing on production.
    if force_stale:
        state_file = state_file.with_suffix(state_file.suffix + ".forced-smoke")
        digest_file = digest_file.with_suffix(digest_file.suffix + ".forced-smoke")
        log(f"FORCED_SMOKE --force-stale={force_stale}: state/digest redirected to "
            f"{state_file.name} / {digest_file.name}; production state is NOT touched")

    try:
        rows = census()
    except Exception as exc:  # fail-open: probe failure never pages, never bounces cron
        log(f"FAIL_OPEN census error: {exc}")
        return 0
    if not rows:
        log("FAIL_OPEN census returned 0 parseable rows (separator/shape drift? re-check psql cmd)")
        return 0

    now = now_epoch()
    digest, majors_bad, tail_bad = evaluate(rows, force_stale, now, retired_set())

    for line in digest:
        log(f"digest {line}")
    for v, s in tail_bad:
        log(f"LONGTAIL_BREACH {v} lag={s} (digest-only by tier policy — never pages)")

    # R3 — Detect → RECOVER → Verify → Alert. Attempt a bounded targeted re-label of each
    # breaching major, then re-census: a major that HEALS drops out of majors_bad here and
    # never pages (silent — recovery alerts are noise). A synthetic --force-stale venue has
    # no real target, so it is skipped (the page path still proves the two-tier contract).
    still_breaching = {v for v, _ in majors_bad}
    attempted: list[str] = []  # the venues this run's recovery step actually ran for (D3's input)
    if RECOVERY_ENABLED and majors_bad:
        attempted = [v for v, _ in majors_bad if v != force_stale and attempt_recovery(v)]
        if attempted:
            log(f"RECOVERY re-census after targeted re-label of {attempted}")
            try:
                rows = census()
                now = now_epoch()
                digest, majors_bad, tail_bad = evaluate(rows, force_stale, now)
                still = {v for v, _ in majors_bad}
                # D3 — the POST-recovery view is what the capacity page must be judged against.
                still_breaching = still
                healed = [v for v in attempted if v not in still]
                if healed:
                    log(f"RECOVERY_HEALED {healed} — silent, no page")
                for line in digest:
                    log(f"post-recovery digest {line}")
            except Exception as exc:  # verify failed → fall through to the page path on the pre-recovery view
                log(f"RECOVERY re-census FAIL_OPEN: {exc}")
                # We attempted repairs and then could not confirm what healed. That is a
                # NON-ANSWER, and passing the stale pre-recovery set would let the page name a
                # venue we may well have just fixed. None => drop nothing, claim nothing.
                still_breaching = None

    # OPS-DEPLOY-LABELER-WINDOW-W1 CH1 — ONE digest line for the truncation RATE.
    #
    # DIGEST-ONLY, never a page. Truncation is safe (graceful-stop checkpoints) and self-healing
    # (the rotation sorts a missed venue first the next night), so paging on it would be recovery
    # chatter. But 34% of nights ending early went uncounted for weeks, and a degradation made
    # SAFE without being made VISIBLE runs until something unrelated trips over it. A single
    # truncated night is noise; the RATE is the finding.
    try:
        runs = lta.parse_runs(Path(lta.LOG_PATH).read_text(errors="replace"))
        if runs:
            starts = lta.container_starts((lta._iso(runs[0]["started_at"])).strftime("%Y-%m-%d"))
            st = lta.summarise(runs, starts)
            log(f"digest TRUNCATION rate={st['truncation_rate_pct']}% "
                f"({st['truncated']}/{st['n']} runs over {st['window_days']}d, "
                f"{st['first_run']}..{st['last_run']}) attributed_to_deploy={st['attributed_to_deploy']} "
                f"({st['attributed_share_pct']}%)")
        else:
            log("digest TRUNCATION INDETERMINATE: parsed zero runs from the labeler log")
    except Exception as exc:  # fail-open: the truncation line must never break the page path
        log(f"digest TRUNCATION INDETERMINATE: {exc}")

    # Objective #2 backstop: forward the labeler's DETECTOR_ENVELOPE from the last nightly run
    # (the wrapper owns severity/cooldown/DRY_RUN gates). Independent of the page path, but NOT
    # independent of the recovery step above — it is handed the POST-recovery breach set so it
    # cannot page for a venue this same invocation already repaired.
    try:
        state = json.loads(state_file.read_text()) if state_file.exists() else {}
    except Exception:
        state = {}

    # OPS-BDIR-V3-PANEL-READINESS-W1 CH2 R3 — the per-venue COVERAGE arm (its own token; independent of
    # the frontier page path above and of the capacity forward below). Its streak lives in the SAME
    # state file (so a --force-stale smoke's SEC-30 redirect isolates it too) under its own key.
    _, coverage_state = coverage_arm(wrapper, now, state.get("coverage"))

    forward_capacity_signal(wrapper, still_breaching=still_breaching, attempted=set(attempted))

    prior: dict[str, int] = state.get("consecutive", {})
    # A healed venue drops out of state entirely (no zero-key accumulation);
    # only currently-breaching MAJORS are tracked (long-tail never pages).
    consecutive = {v: prior.get(v, 0) + 1 for v in {v for v, _ in majors_bad}}

    to_page = [(v, s) for v, s in majors_bad if consecutive.get(v, 0) >= CONSECUTIVE_TO_PAGE]
    if to_page:
        body = build_alert_body(to_page, consecutive)
        try:
            subprocess.run([wrapper, ALERT_ID, SEVERITY, "-"], input=body, text=True, timeout=60)
            log(f"PAGE_SENT_TO_WRAPPER majors={[v for v, _ in to_page]} (wrapper owns cooldown/DRY_RUN gates)")
        except Exception as exc:
            log(f"FAIL_OPEN wrapper error: {exc}")
    elif majors_bad:
        log(f"MAJOR_BREACH_DAY_1 {[v for v, _ in majors_bad]} — sustained-drift gate holds page until day {CONSECUTIVE_TO_PAGE}")

    try:
        state_file.parent.mkdir(parents=True, exist_ok=True)
        state_file.write_text(json.dumps({"consecutive": consecutive, "coverage": coverage_state, "updated": now}, indent=1))
        digest_file.parent.mkdir(parents=True, exist_ok=True)
        digest_file.write_text("\n".join(digest) + "\n")
    except Exception as exc:
        log(f"FAIL_OPEN state/digest write error: {exc}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
