/**
 * tests/fixtures/weight-budget-replay.ts — OPS-UPSTREAM-ACQUISITION-ACCOUNTING-W1 CH2.
 *
 * A DETERMINISTIC contended corpus of acquire() calls and a replayer, used to prove that per-caller
 * accounting changed NO admission decision. The replayer takes the WeightBudget CLASS as a parameter,
 * so the identical corpus runs against the pre-wave implementation (origin/main 2dcafc2a, to produce
 * the committed golden) and against the current one (tests/unit/weight-budget-replay-identity.test.ts).
 *
 * The corpus is generated by a fixed-seed LCG — never Math.random — so it is reproducible byte for
 * byte. Several "processes" (WeightBudget instances) share ONE ledger + lock, exactly as containers'
 * short-lived crons and PID 1 do; the injected clock is shared, and the injected batch `sleep`
 * advances it, so a waiting batch call rolls windows deterministically and can end in a skip.
 * Every grant / wait / skip / throw path is exercised (the test asserts each occurred).
 */
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

export interface ReplayCall { i: number; proc: number; dt: number; cls: 'interactive' | 'batch'; weight: number; caller: string }
export interface ReplayResult {
  i: number; proc: number; tBefore: number; tAfter: number; cls: string; weight: number; caller: string;
  outcome: string; // ok | throw:<secondsToRoll> | skip | error:<name>
  ledger: { windowStartMs: number; used: number; batchUsed: number; interactiveUsed: number; waits: number; skips: number; throws: number };
}
export interface ReplayTrace { config: typeof CONFIG; results: ReplayResult[]; windowLines: string[] }

export const CONFIG = { ceilingPerMin: 100, interactiveReserve: 40, windowMs: 60_000, maxBatchWaitMs: 90_000, processes: 3, calls: 360, seed: 20260926, t0: 1_790_400_000_000 };
const CALLERS = ['seed:5m:hl', 'seed:5m:promoted', 'backfill_outcomes_cron', 'signal_perf_backfill', 'get_trade_call', 'scan_trade_calls', 'unattributed:index'];

function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => { s = (Math.imul(s, 1664525) + 1013904223) >>> 0; return s / 0x1_0000_0000; };
}

/** The fixed corpus: bursts (dt 0-400 ms) punctuated by gaps (up to 25 s), mixed classes and weights. */
export function buildCorpus(): ReplayCall[] {
  const r = lcg(CONFIG.seed); const out: ReplayCall[] = [];
  for (let i = 0; i < CONFIG.calls; i++) {
    const burst = r() < 0.8;
    const dt = burst ? Math.floor(r() * 400) : Math.floor(r() * 25_000);
    const cls = r() < 0.55 ? 'batch' : 'interactive';
    let weight = 1 + Math.floor(r() * 24);
    // ~4% oversized requests: a batch request above the batch cap (ceiling − reserve = 60) waits across
    // window rolls until maxBatchWaitMs, then SKIPS; an interactive request above the ceiling THROWS.
    // Without these a sequential replay can never reach the skip path (the rolled window is empty).
    if (r() < 0.04) weight = cls === 'batch' ? 61 + Math.floor(r() * 15) : 101 + Math.floor(r() * 10);
    out.push({ i, proc: Math.floor(r() * CONFIG.processes), dt, cls, weight, caller: CALLERS[Math.floor(r() * CALLERS.length)] });
  }
  return out;
}

type BudgetCtor = new (opts: Record<string, unknown>) => { acquire(w: number, c: 'interactive' | 'batch'): Promise<void>; _readLedger(): ReplayResult['ledger'] };
type RunCaller = <T>(caller: string, fn: () => T) => T;

/**
 * Replay `buildCorpus()` sequentially against `Budget`. `runAsCaller` (when given) wraps each call so a
 * caller-aware implementation sees the corpus caller; the pre-wave implementation ignores it.
 */
export async function replay(Budget: BudgetCtor, runAsCaller?: RunCaller, dir?: string): Promise<ReplayTrace> {
  const base = dir ?? fs.mkdtempSync(path.join(os.tmpdir(), 'wb-replay-'));
  const ledgerPath = path.join(base, 'algovault-replay-weight.json');
  const lockPath = path.join(base, 'algovault-replay-weight.lock');
  const clock = { t: CONFIG.t0 };
  const logs: string[] = [];
  const procs = Array.from({ length: CONFIG.processes }, () => new Budget({
    venue: 'Replay', ledgerPath, lockPath, ceilingPerMin: CONFIG.ceilingPerMin, interactiveReserve: CONFIG.interactiveReserve,
    windowMs: CONFIG.windowMs, maxBatchWaitMs: CONFIG.maxBatchWaitMs, staleLockMs: 60_000, lockRetryMs: 1,
    now: () => clock.t, sleep: async (ms: number) => { clock.t += ms; }, log: (l: string) => logs.push(l),
  }));
  const results: ReplayResult[] = [];
  for (const c of buildCorpus()) {
    clock.t += c.dt;
    const tBefore = clock.t;
    let outcome = 'ok';
    const run = () => procs[c.proc].acquire(c.weight, c.cls);
    try { await (runAsCaller ? runAsCaller(c.caller, run) : run()); }
    catch (e) {
      const err = e as { name?: string; code?: string; retryAfterSeconds?: number | null; constructor?: { name?: string } };
      const name = err.constructor?.name ?? err.name ?? 'Error';
      if (name === 'UpstreamRateLimitError') outcome = `throw:${err.retryAfterSeconds}`;
      else if (name === 'WeightBudgetSkipError') outcome = 'skip';
      else outcome = `error:${name}`;
    }
    const l = procs[c.proc]._readLedger();
    results.push({ i: c.i, proc: c.proc, tBefore, tAfter: clock.t, cls: c.cls, weight: c.weight, caller: c.caller, outcome,
      ledger: { windowStartMs: l.windowStartMs, used: l.used, batchUsed: l.batchUsed, interactiveUsed: l.interactiveUsed, waits: l.waits, skips: l.skips, throws: l.throws } });
  }
  const windowLines = logs.filter((l) => { try { return JSON.parse(l).event === 'window'; } catch { return false; } });
  if (!dir) fs.rmSync(base, { recursive: true, force: true });
  return { config: CONFIG, results, windowLines };
}
